services:
  - type: web
    name: unified-trading-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "./render_start.sh"
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PYTHONUNBUFFERED
        value: 1