
# Unified Trading Bot Configuration
# =================================
# This configuration file contains all settings for the unified trading bot
# with lowered thresholds for testing purposes

# Bot Configuration
bot:
  update_interval: 60  # seconds between trading cycles
  max_concurrent_trades: 5
  timezone: "US/Eastern"

# Logging Configuration
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  file: "trading_bot.log"
  max_file_size: "10MB"
  backup_count: 5
  console_output: true

# Trading Configuration
trading:
  watchlist:
    - "SPY"
    - "QQQ"
    - "AAPL"
    - "MSFT"
    - "TSLA"
    - "NVDA"
    - "GOOGL"
    - "AMZN"
  
  market_hours_only: true
  extended_hours: false

# Strategy Configuration
strategies:
  rsi_macd:
    enabled: true
    weight: 0.6
  
  options:
    enabled: true
    weight: 0.4

# Technical Indicators
indicators:
  rsi:
    period: 14
    oversold_threshold: 30
    overbought_threshold: 70
  
  macd:
    fast_period: 12
    slow_period: 26
    signal_period: 9
  
  moving_averages:
    short_period: 20
    long_period: 50

# Signal Configuration (Lowered for Testing)
signals:
  min_strength: 0.3      # Lowered from 0.6 for testing
  min_confidence: 0.5    # Lowered from 0.7 for testing
  max_concurrent: 5
  
  # Signal strength multipliers
  multipliers:
    rsi_extreme: 1.5     # When RSI is in extreme territory
    macd_crossover: 1.3  # When MACD crosses signal line
    volume_spike: 1.2    # When volume is above average
    options_flow: 1.4    # When unusual options activity detected

# Risk Management
risk:
  max_position_size: 0.05      # 5% of portfolio per position
  max_portfolio_risk: 0.20     # 20% total portfolio risk
  max_risk_score: 0.8          # Lowered from 0.6 for testing
  stop_loss_percentage: 0.02   # 2% stop loss
  take_profit_percentage: 0.06 # 6% take profit
  
  # Position sizing
  base_position_size: 1000     # Base position size in dollars
  risk_per_trade: 0.01         # 1% risk per trade

# Options Trading
options:
  enabled: true
  strategies:
    - "long_calls"
    - "long_puts"
    - "covered_calls"
  
  # Options selection criteria (Relaxed for testing)
  min_volume: 50              # Lowered from 100
  min_open_interest: 100      # Lowered from 500
  max_bid_ask_spread: 0.20    # Increased from 0.10
  
  # Expiration preferences
  min_days_to_expiration: 7   # Lowered from 14
  max_days_to_expiration: 45
  preferred_delta_range:
    min: 0.30                 # Lowered from 0.40
    max: 0.70                 # Increased from 0.60

# Market Data
market_data:
  provider: "yfinance"  # yfinance, alpha_vantage, polygon
  update_frequency: 60  # seconds
  
  # Data retention
  history_days: 252     # 1 year of trading days
  intraday_interval: "1m"
  
  # API settings
  rate_limit: 5         # requests per second
  timeout: 30           # seconds

# Database Configuration
database:
  enabled: false
  type: "sqlite"        # sqlite, postgresql, mysql
  path: "trading_bot.db"
  
  # Connection settings (for non-sqlite)
  host: "localhost"
  port: 5432
  username: ""
  password: ""
  database: "trading_bot"

# Notifications
notifications:
  enabled: true
  channels:
    - "console"
    - "file"
  
  # Email notifications (optional)
  email:
    enabled: false
    smtp_server: ""
    smtp_port: 587
    username: ""
    password: ""
    to_addresses: []
  
  # Webhook notifications (optional)
  webhook:
    enabled: false
    url: ""
    headers: {}

# Backtesting
backtesting:
  enabled: false
  start_date: "2023-01-01"
  end_date: "2024-01-01"
  initial_capital: 100000
  commission: 0.005     # 0.5% commission per trade

# Paper Trading
paper_trading:
  enabled: true
  initial_balance: 100000
  track_performance: true
  save_trades: true

# Development/Testing Settings
development:
  debug_mode: false
  mock_market_data: false
  simulate_latency: false
  test_mode: true       # Enables relaxed thresholds
  
  # Testing overrides
  force_signals: false  # Generate test signals regardless of market conditions
  signal_frequency: 300 # Generate test signal every 5 minutes when force_signals=true
