
# Docker Compose for Unified Trading Bot
# ======================================
# For local development and testing

version: '3.8'

services:
  trading-bot:
    build: .
    container_name: unified-trading-bot
    environment:
      - LOG_LEVEL=INFO
      - TEST_MODE=true
      - LIVE_TRADING=false
      - UPDATE_INTERVAL=60
      - TRADING_BOT_SIGNALS_MIN_STRENGTH=0.3
      - TRADING_BOT_RISK_MAX_RISK_SCORE=0.8
    volumes:
      - ./logs:/app/logs
      - ./config.yaml:/app/config.yaml
      - ./cache:/app/cache
    restart: unless-stopped
    command: ["python", "unified_trading_bot.py", "--dry-run", "--log-level", "INFO"]

  # Optional: Add a database service
  # postgres:
  #   image: postgres:15
  #   container_name: trading-bot-db
  #   environment:
  #     POSTGRES_DB: trading_bot
  #     POSTGRES_USER: trading
  #     POSTGRES_PASSWORD: trading_password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"

  # Optional: Add Redis for caching
  # redis:
  #   image: redis:7-alpine
  #   container_name: trading-bot-redis
  #   ports:
  #     - "6379:6379"

# volumes:
#   postgres_data:
